#!/usr/bin/env python2.7

"""
Simple definition lookup application for command line terminals.
Queries XML from services.aonaware.com
Usage: `define <word>` where <word> is a command line argument

Author:   Ryan James Spencer
Date:     7/3/15
Version:  1.0.0
"""

import argparse
import re
import sys
import urllib2
import xml.etree.ElementTree as ET


def setup_args():
    argParser = \
        argparse.ArgumentParser(description="Commandline dictionary!")
    argParser.add_argument('word', metavar='w', type=str, nargs=1,
                           help='A word to define')
    args = vars(argParser.parse_args())
    query = ''.join(args['word'])
    return query


def construct_url(query):
    root = "http://services.aonaware.com"
    req_path = "/DictService/DictService.asmx/Define?word="
    url = "{0}{1}{2}".format(root, req_path, query)
    return url


def find_def(query):
    suffix = re.compile(r'.*\.py.*')
    if re.match(suffix, sys.argv[0]):
        print("You are attempting to run this script directly.")
        print("Please rerun with 'define <word>'")
    else:
        # Query the service and construct an ElementTree
        url = construct_url(query)
        response_file = urllib2.urlopen(url)
        tree = ET.parse(response_file)
        root = tree.getroot()
        ns = 'http://services.aonaware.com/webservices/'
        dicts = root.findall('.//{{{0}}}Name'.format(ns))
        defs = root.findall('.//{{{0}}}WordDefinition'.format(ns))
        results = zip(dicts, defs)
        for s, d in results:
            print '{}\n{}'.format(s.text, d.text)


if __name__ == '__main__':
    query = setup_args()
    find_def(query)
